[providers]
node = {}
python = {}

[phases.setup]
nixPkgs = ['...', 'nodejs', 'python311', 'ffmpeg']

[phases.install]
cmds = [
    'npm install',
    'cd python && python3 -m venv venv && ./venv/bin/pip install -r requirements.txt'
]

[start]
cmd = 'bash start.sh'
