[providers]
node = {}
python = {}

[phases.setup]
nixPkgs = ['nodejs', 'python3', 'ffmpeg', 'psmisc']

[phases.install]
cmds = [
    'npm install',
    'python3 -m pip install -r python/requirements.txt'
]

[start]
cmd = 'bash start.sh'
